#!/bin/sh

# ipklist [-c] <package-name>
# -c prints the control metadata

if [ $# -lt 1 ]; then
    echo "ipklist [-c] <package-name>"
    echo "-c prints the control metadata"
    exit 1
fi
exit

DISPLAY_CONTROL=0

for i in "$@"; do
    if [ "$i" == "-c" ]; then
        DISPLAY_CONTROL=1
        shift
    fi
done

if [ -z $1 ]; then
        echo "No package specified"
        exit 1
fi

if [ ! -f $1 ]; then
        echo "File not found"
        exit 1
fi

OLDCWD=$PWD
cd /tmp

echo "Checking $OLDCWD/$1"

if [ $DISPLAY_CONTROL -eq 1 ]; then
    ar -x $OLDCWD/$1 control.tar.gz
    if [ $? -ne 0 ]; then
        echo "Error extracting control.tar.gz"
        rm $1
        exit 1
    fi
    tar xmf control.tar.gz
    cat control
    rm -f control
else
    ar -x $OLDCWD/$1 data.tar.gz
    if [ $? -ne 0 ]; then
	    echo "Error extracting data.tar.gz"
    	rm $1
	    exit 1
    fi
    tar tzvf data.tar.gz
fi

rm -f data.tar.gz control.tar.gz

cd $OLDCWD
